name: earthpy_docs
channels:
- conda-forge
dependencies:
- python=3.7
- geopandas=0.7.0
- rasterio=1.1.3
- fiona=1.18.13
- sphinx=1.8.4
- sphinx_rtd_theme=0.4.3
- m2r=0.2.1
- sphinx-gallery=0.2.0
# To make conda resolution faster - following geopandas
- scikit-image=0.16.2
- libgdal =3.0.4
- pyproj=2.6.0
- gdal=3.0.4
- shapely=1.7.0
